<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pits_mailchimp"
 *
 * Auto generated by Extension Builder 2015-04-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PITS Mailchimp Subscriber',
	'description' => 'This extension will shows a simple subscribe form in front end and several options of extensibility and options for using subscribers from fe_user table or custom TCA for creating mailchimp users.',
	'category' => 'plugin',
	'author' => 'HOJA M A',
	'author_email' => 'hoja.ma@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);